language: ruby
deploy:
  provider: heroku
  api_key:
    secure: mv+ud1FqNIISg0PnptHpA4+WF4wy9kyVG4f+/XHZDQJmwLB/ud2laUIIHn6H1BjDhxGS2wvacBXDvesAU0lReNKXjTxJJhDdiTBS5oQIGKejc+v/81GA9acAycaXgkQmH4mE8yz3+ttR1+Rkea9uDAapFMFXQTevurlA9vKi8XVJFjiY3ikFm1mYgpT1aSh2h9yUFrvJpPwhFpj2eFoR8TYc4SVWXrFhfiUdbP8tl7K1WD8FTcdWeKLAUGGZ0RSX6AGoku4V2A0Nh6UkvgryRALj8by8w3W86gGGSENk0fPna7+1FaK39Equ3Sg1JDAmCb51fZiYi402zLOUyLLHRslpuSKoYr8Ry7TIG2URCI/F41Xyx+DOrAJXCbS7q3KM96io4sF8NhP0fuFPuSz1DVGA+rrMlJzgrFj1d2Whr8Cq1IaRboKKsS/zPbM7eTlbFFY1qXoc2VXwaL9HVtcKke2yENcv4wLRRbv/e7CyvFTCsP3IoyQATqxr2obvZ/j7I4uAFp/ZprJ8LpEvCwr3KgsIMBUol1hluPKTzBSanEMUnlKS+KaKXJ5s9jPPwoeLz2CjRLkA2QCG1DVv5MnxZvNwSGMy+p5q0SoccF7LG7Zy/oBN9m4JHqxEMpDK/aSAjqjsB+SSHv8VZNk2kSNqvLlnmpke3FgiQ3CjrbYb2AA=
  app: secret-sands-23033
  on:
    repo: ajleon/t2_integra
